=== CladussBro/LenguajeDeMarcas/1.XML/U1_T1/DTD_XML/DTD5.dtd
<!ELEMENT partido (equipo+) >
<!ELEMENT equipo (goles*, tarjetas*) >
<!ELEMENT goles (gol*) >
<!ELEMENT gol (jugador, minuto) >
<!ELEMENT jugador (#PCDATA) >
<!ELEMENT minuto (#PCDATA) >
<!ELEMENT tarjetas (tarjeta*) >
<!ATTLIST equipo name CDATA #REQUIRED
                    tipo CDATA #REQUIRED >
<!ATTLIST gol tipo CDATA #REQUIRED >
<!ELEMENT tarjeta (jugador) >
<!ATTLIST tarjeta tipo CDATA #REQUIRED >

=== CladussBro/LenguajeDeMarcas/1.XML/U1_T1/DTD_XML/DTD5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE partido SYSTEM "DTD5.dtd">
<partido>
    <equipo name="Betis" tipo="local">
        <goles>
            <gol tipo="penalti">
                <jugador>Joaquín</jugador>
                <minuto>23</minuto>
            </gol>
            <gol tipo="penalti">
                    <jugador>Joaquín</jugador>
                    <minuto>52</minuto>
                </gol>
        </goles>
        <tarjetas>
            <tarjeta tipo="amarilla">
                <jugador>Joaquín</jugador>
            </tarjeta>
            <tarjeta tipo="roja">
                    <jugador>Joaquín</jugador>
                </tarjeta>
        </tarjetas>
    </equipo>
    <equipo name="Sevilla" tipo="visitante">
            <goles>
                <gol tipo="penalti">
                    <jugador>Banega</jugador>
                    <minuto>23</minuto>
                </gol>
            </goles>
            <tarjetas>
                <tarjeta tipo="roja">
                        <jugador>Banega</jugador>
                    </tarjeta>
            </tarjetas>
        </equipo>
</partido>
