=== CladussBro/LenguajeDeMarcas/1.XML/U1_T1/DTD_XML/DTD6.dtd
<!ELEMENT movies (movie+)>
<!ELEMENT movie (title, nationality?, directors, actors)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT nationality (#PCDATA)>
<!ELEMENT directors (director+)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT actors (actor+)>
<!ELEMENT actor (#PCDATA)>
<!ATTLIST movie type (adventure|science_fiction|thriller|other)
                    review (1|2|3|4|5) "3">

=== CladussBro/LenguajeDeMarcas/1.XML/U1_T1/DTD_XML/DTD6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE movies SYSTEM "DTD6.dtd">
<movies>
    <movie type="adventure" review="3">
        <title>Oblivion: El tiempo del olvido</title>
        <nationality>Americana</nationality>
        <directors>
            <director>Joseph Kosinski</director>
        </directors>
        <actors>
            <actor>Tom Cruise</actor>
            <actor>Andrea Riseborough</actor>
            <actor>Olga Kurylenko</actor>
        </actors>
    </movie>
    <movie type="thriller" review="3">
            <title>DÃ©jame salir</title>
            <directors>
                <director>Jordan Peele</director>
                <director>Jordan Peele</director>
            </directors>
            <actors>
                <actor>Tom Cruise</actor>
                <actor>Andrea Riseborough</actor>
                <actor>Olga Kurylenko</actor>
            </actors>
        </movie>
</movies>
