=== CladussBro/LenguajeDeMarcas/1.XML/U1_T1/XML_XSD/clase1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
elementFormDefault ="qualified">
<xs:element name="clase">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="alumno" type="xs:string"/>
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                        <xs:element name="apellidos" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            <xs:element name="profesor" type="xs:string"/>
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                        <xs:element name="apellidos" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== CladussBro/LenguajeDeMarcas/1.XML/U1_T1/XML_XSD/clase.xml
<?xml version="1.0" encoding="UTF-8"?>
<clase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="clase1.xsd">
<clase>
   <alumno>
        <nombre>Claudia Nerea</nombre>
        <apellidos>Borrachero Mallofret</apellidos>
    </alumno>
    <profesor>
        <nombre>Juan Diego</nombre>
        <apellidos>Pérez</apellidos>
    </profesor>
    <profesor>                
        <nombre>Chema</nombre>
        <apellidos>García</apellidos>
    </profesor>
</clase>
</clase>
